### ISSUE TITLE
Document SparsePFT

### ISSUE THREAD

**Issue by zsunberg** [WhiffleFish/PFT-DPW.jl#2]
@WhiffleFish can we document how to use SparsePFT? Is it just the same as DPW, but with alpha_o = 0?

**Comment by zsunberg** [comment]
Or does SparsePFT have a separate implementation (I seem to remember that it had only one heap allocation?)

**Comment by WhiffleFish** [comment]
Just added a `SparsePFTSolver` convenience method as well as some short documentation in the readme

**Comment by zsunberg** [comment]
Awesome! Love the `0 allocations`!
